services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "3000"
    deploy:
      mode: replicated
      replicas: 3

  web:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
